version: '3'

services:
  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092      

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  aerospike:
    image: aerospike/aerospike-server:3.14.1.10
    command: ['--config-file', '/opt/aerospike/etc/aerospike.conf']
    volumes:
      - ./aerospike:/opt/aerospike/etc
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'

  amc:
    image: aerospike/amc:4.0.25
    ports:
      - '8081:8081'
    depends_on:
      - aerospike

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example