version: '3'

services: 
    elasticsearch:
        image: elasticsearch:7.6.1
        environment:
          - discovery.type=single-node
        volumes:
          - ./elasticsearch:/usr/share/elasticsearch/data
        ports:
          - '9200:9200'